### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#1]
#### Realizar la sección de Contactos con la siguiente información: 
- [ ] Ubicación de la Facultad de Negocios y Tecnologías Campus Ixtaczoquitlán (Carretera Estatal Sumidero - Dos Rios, Km 1, Ixtaczoquitlán Veracruz, México)
- [ ]           2. Incluir mapa de Google Maps donde muestre la ubicación
- [ ]           3. Horario y días en los que se pueda asistir (Lunes a Viernes 10:00 - 14:00 hrs)
> En caso de faltar información o de agregar más, acudir con el CA.

### Estilos del Landing Page
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Botones
- [ ] Color: #3D708D
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![Captura de pantalla de 2022-11-28 04-32-50](https://user-images.githubusercontent.com/62484066/205234596-a4cd2088-9c04-49c1-9258-81105b15252e.png)
![Captura de pantalla de 2022-11-28 04-33-00](https://user-images.githubusercontent.com/62484066/205234599-bc20a11d-130b-4855-9248-c98d9075d1e7.png)
![Captura de pantalla de 2022-11-28 04-33-04](https://user-images.githubusercontent.com/62484066/205234600-0b802c44-8782-493e-932b-eb03d19be27d.png)
![Captura de pantalla de 2022-11-28 04-33-08](https://user-images.githubusercontent.com/62484066/205234602-2143cba0-890a-4fc1-a065-2e5f3f34e73c.png)
![Captura de pantalla de 2022-11-28 04-33-11](https://user-images.githubusercontent.com/62484066/205234606-1f1c457a-282d-44a6-bb2c-b3654f9620c0.png)
