### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#2]
#### Realizar la sección de _¿Quienes somos?_ con la siguiente información de los docentes: 
- [ ] Nombre Completo
- [ ] Correo institucional
- [ ] Perfil Académico
- [ ] Perfil Laboral 
> En caso de faltar información o de agregar más, acudir con el CA.

### Estilos de About Us
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Cards
- [ ] Color de etiquetas h1/h2: #3D708D
- [ ] Color de letra: Negro
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo
- [ ] Color de contorno:  #3D708D

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![Captura de pantalla de 2022-11-28 04-40-17](https://user-images.githubusercontent.com/62484066/205236567-41142fa1-8e4c-4941-881d-26e0c7b05490.png)
