### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#3]
#### Pedir la siguiente información: 
- [ ] Correo electrónico
- [ ] Contraseña
> En caso de faltar información o de agregar más, acudir con el CA.

### Estilos del Sign in
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Botones
- [ ] Color: #3D708D
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![Captura de pantalla de 2022-11-28 04-33-37](https://user-images.githubusercontent.com/62484066/205239284-680a6ec9-0de0-4568-9beb-4bb59426d1cd.png)
