### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#4]
#### Pedir la siguiente información: 
>Directivo
- [ ] Nombre
- [ ] Apellido
- [ ] Puesto/Cargo
- [ ] Género
- [ ] Grado de estudios (select)  _**campo obligatorio**_
- [ ] Lada
- [ ] Teléfono
- [ ] Correo Electrónico _**campo obligatorio**_
- [ ] Contraseña _**campo obligatorio**_
_Establecer nivel de contraseña (débil, media, fuerte)_
- [ ] Verificar la contraseña _**campo obligatorio**_
- [ ] Correo alterno

>Empresa
- [ ] Nombre de Empresa  _**campo obligatorio**_
- [ ] Giro  _**campo obligatorio**_
- [ ] Años de antigüedad  _**campo obligatorio**_
- [ ] Número de colaboradores (select)  _**campo obligatorio**_
- [ ] Lada
- [ ] Teléfono Corporativo
- [ ] País
- [ ] Estado
- [ ] Ciudad
- [ ] Dirección
- [ ] Código Postal

> En caso de faltar información o de agregar más, acudir con el CA.

### Estilos del Sign up
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Botones
- [ ] Color: #3D708D
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo

>Campos Obligatorios

- [ ] Contorno color verde para identificar que son los campos obligatorios

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![
![Captura de pantalla de 2022-11-28 04-35-31](https://user-images.githubusercontent.com/62484066/205241657-f8f7e2d1-e73e-4ecb-8e5c-7e3cfa02fda2.png)
Captura de pantalla de 2022-11-28 04-35-31](https://user-images.githubusercontent.com/62484066/205239525-242f6ee4-3ee0-41c9-9bc8-516fa4e83cdf.png)
