### ISSUE TITLE
Encuesta Procesos Adminstrativos

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#5]
## Sección Encuesta

- [ ]  Al responder SI en una pregunta, se desglosarán un par de preguntas
- [ ]  Al responder NO en una pregunta, no se desglosará nada y podrá seguir a la siguiente pregunta

> Acudir con el CA para la entrega completa de la documentación que se pondrá en las secciones de la encuesta.

### Estilos del menú y de las encuestas
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Botones
- [ ] Color: #3D708D
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![Captura de pantalla de 2022-11-28 04-37-46](https://user-images.githubusercontent.com/62484066/205242431-491302b9-1e9e-4799-9508-5eab862f98ea.png)
![Captura de pantalla de 2022-11-28 04-43-28](https://user-images.githubusercontent.com/62484066/205242565-97e0f106-00fb-431e-924d-f3e61416a3a9.png)
