### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#6]
####  Realizar el perfil de Usuario basándose en el mockup que se adjunta
- [ ] En esta sección deben aparecer los resultados de cada sección que se respondió en la encuestra
> En caso de faltar información o de agregar más, acudir con el CA.

### Estilos del User Profile
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Sidebar/Barra de Navegación Lateral
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px

> Botones
- [ ] Color: #3D708D
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![Captura de pantalla de 2022-11-28 04-54-04](https://user-images.githubusercontent.com/62484066/205245510-537c0a8b-47f6-423e-aa39-1fad109aeecc.png)
![Captura de pantalla de 2022-11-28 04-54-37](https://user-images.githubusercontent.com/62484066/205245551-3c7f3058-ad61-4627-bc35-d7ca743d8528.png)
![Captura de pantalla de 2022-11-28 04-54-54](https://user-images.githubusercontent.com/62484066/205245594-d8889d9b-1b14-4a84-897a-35122df3dc80.png)
![Captura de pantalla de 2022-11-28 04-54-56](https://user-images.githubusercontent.com/62484066/205245599-21b6066f-1649-474b-a934-2f2de1a4704f.png)
![Captura de pantalla de 2022-11-28 04-54-57](https://user-images.githubusercontent.com/62484066/205245603-302d6e5c-071c-4621-9bea-2b4584a2b9e2.png)
