### ISSUE TITLE
Admin Profile

### ISSUE THREAD

**Issue by arlycr20** [arlycr20/adn-empresarial#7]
####  Realizar el perfil de Usuario basándose en el mockup que se adjunta
- [ ] En esta sección deben aparecer luna tabla con todos los usuarios registrados, sus datos personales, y en otra sección los una tabla con los resultados de cada usuario, asi como el puntaje de sus respuestas y que dicha tabla pueda ser exportada a excel 
> En caso de faltar información o de agregar más, acudir con el CA.

### Estilos del Admin Profile
 
> Navbar/Barra de Navegación
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Color de la barra de navegación: #003857
- [ ] Tamaño de la letra: 20px

> Sidebar/Barra de Navegación Lateral
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px

> Botones
- [ ] Color: #3D708D
- [ ] Color de letra: Blanco
- [ ] Tipo de letra/fuente: Raleway
- [ ] Contorno: Redondo

> Footer/ Pie de página
- [ ] Color de fondo: #09080E
- [ ] Color de letra: #6c757d
- [ ] Tamaño de letra: 16px
- [ ] Tipo de letra/fuente: Raleway

## Mockups de referencia
![Captura de pantalla de 2022-11-28 04-54-04](https://user-images.githubusercontent.com/62484066/205245510-537c0a8b-47f6-423e-aa39-1fad109aeecc.png)
